version: "2"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:7.1.1
    ports:
      - 8085:3000
    user: "472"
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=admin
