version: "3"

services:
  influxdb:
    // https://hub.docker.com/_/influxdb
    image: influxdb:1.8.3
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    // https://hub.docker.com/r/grafana/grafana
    image: grafana/grafana:7.3.7
    ports:
      - 8085:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SERVER_ROOT_URL=http://192.168.77.6:8085
      - GF_SECURITY_ADMIN_PASSWORD=admin
